### ISSUE TITLE
Bot Features for Initial Deployment

### ISSUE THREAD

**Issue by ColdSunERA** [PCGamingEra/Daedalus#1]
### List of features that should be completed before deploying the bot to the discord:
**Moderator Commands:**
- [ ] Configurable setting to specify mod role
- [ ] Create joinable roles
- [ ] Remove joinable roles
- [ ] Enable commands for specific roles in specific or global channels
- [ ] Disable commands for specific roles in specific or global channels  
- [ ] Change bot prefix (no hard-coding it this time)
- [ ] Ban log channel
- [ ] Unban log channel
- [ ] Members leaving/kicked channel
- [ ] Messages deleted channel
- [ ] Set GiftBot Channel

**User Commands:**
- [ ] List all roles that can be joined
- [ ] Join a role
- [ ] Leave a role
- [ ] List available commands, specific to the user (in a DM)
- [ ] Ping bot to verify it's running
- [ ] Help command to link to a support post
- [ ] Bug report command to DM ColdSun bug reports (May move this to a channel on it's own server)
- [ ] Claim GiftBot Key
- [ ] Contribute GiftBot Key

**Comment by yaskael** [comment]
A Welcome message on general channel when user joins. Maybe also a DM to new users when they join for the first time with the server rules and useful information

**Comment by yaskael** [comment]
Calendar function (ics) to have bot announce new releases from opencritic calendar.
